name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, windows-latest]
         build_type: [Release, Debug]
         include:
           - os: windows-latest
             c_compiler: gcc
             cpp_compiler: g++
           - os: ubuntu-latest
             c_compiler: gcc
             cpp_compiler: g++
           - os: ubuntu-latest
             c_compiler: clang
             cpp_compiler: clang++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # -------------------------------
    # Install vcpkg
    # -------------------------------
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git vcpkg
        ./vcpkg/bootstrap-vcpkg.sh || .\vcpkg\bootstrap-vcpkg.bat

    # -------------------------------
    # Install dependencies via vcpkg
    # -------------------------------
    - name: Install libraries with vcpkg
      run: |
        ./vcpkg/vcpkg install glfw3 freetype glew
      shell: bash
      if: matrix.os == 'ubuntu-latest'

    - name: Install libraries with vcpkg on Windows
      run: |
        vcpkg\vcpkg.exe install glfw3 freetype glew
      if: matrix.os == 'windows-latest'

    # -------------------------------
    # Configure CMake
    # -------------------------------
    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -S ${{ github.workspace }}

    # -------------------------------
    # Build Project
    # -------------------------------
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    # -------------------------------
    # Run Tests
    # -------------------------------
    #- name: Run tests
    #  working-directory: build
    #  run: ctest --build-config ${{ matrix.build_type }}
