name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, windows-latest]
         build_type: [Release, Debug]
         include:
           - os: windows-latest
             c_compiler: gcc
             cpp_compiler: g++
           - os: ubuntu-latest
             c_compiler: gcc
             cpp_compiler: g++
           - os: ubuntu-latest
             c_compiler: clang
             cpp_compiler: clang++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # -------------------------------
    # Install Dependencies on Ubuntu
    # -------------------------------
    - name: Install Dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libfreetype6-dev libglew-dev build-essential cmake

    # -------------------------------
    # Install Dependencies on Windows (MinGW)
    # -------------------------------
    - name: Install Dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install mingw -y
        choco install glfw freetype glew -y
        setx PATH "%PATH%;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"

    # -------------------------------
    # Configure CMake
    # -------------------------------
    - name: Configure CMake
      run: cmake -B build \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -S ${{ github.workspace }}

    # -------------------------------
    # Build Project
    # -------------------------------
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    # -------------------------------
    # Run Tests
    # -------------------------------
    #- name: Run tests
    #  working-directory: build
    #  run: ctest --build-config ${{ matrix.build_type }}